services:
  app:
    image: 'mcr.microsoft.com/devcontainers/go:1-1.22-bookworm'
    command: sleep infinity
    volumes:
      - ../../:/workspace
  reverse_proxy:
    build:
      context: ../../cmd/reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
